# Generated by Django 5.1.3 on 2024-12-06 09:49

import dashboard.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='Default Team', max_length=100)),
                ('event_name', models.CharField(default='Default Team', max_length=100)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_time', models.TimeField(default=dashboard.models.get_current_time)),
            ],
        ),
    ]
